[build]
  # The command to build your site
  command = "echo 'default context'"

  # The directory that contains the build output
  publish = "build-output/"

  # The directory that contains the source files for your project
  base = "project/"
